# Generated by Django 3.1.2 on 2020-11-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotzone', '0003_patientdetail_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedetail',
            name='patient',
        ),
        migrations.DeleteModel(
            name='PatientDetail',
        ),
    ]
