# Generated by Django 3.1.2 on 2020-11-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotzone', '0004_auto_20201117_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('idNumber', models.CharField(max_length=10)),
                ('dataOfBirth', models.DateField()),
            ],
        ),
    ]
