# Generated by Django 3.1.2 on 2020-11-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotzone', '0006_casedetail_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitedlocationdetail',
            name='caseNumber',
        ),
        migrations.AddField(
            model_name='casedetail',
            name='visitedLocation',
            field=models.ManyToManyField(to='hotzone.VisitedLocationDetail'),
        ),
    ]
