# Generated by Django 3.1.2 on 2020-11-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotzone', '0008_auto_20201117_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedlocationdetail',
            name='category',
            field=models.CharField(choices=[('Residence', 'Residence'), ('Workplace', 'Workplace'), ('Visit', 'Visit')], max_length=10),
        ),
    ]
