# Generated by Django 3.1.2 on 2020-11-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50, null=True)),
                ('x', models.CharField(max_length=50)),
                ('y', models.CharField(max_length=50)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('catagory', models.CharField(choices=[('R', 'Residence'), ('W', 'Workplace'), ('V', 'Visit')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_num', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('common_name', models.CharField(max_length=50)),
                ('max_infection_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_date', models.DateField()),
                ('source', models.CharField(choices=[('L', 'LOCAL'), ('I', 'IMPORTED')], max_length=1)),
                ('infecting_virus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotzone.virus')),
                ('location_visited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotzone.locationvisited')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotzone.patient')),
            ],
        ),
    ]
