# Generated by Django 3.1.2 on 2020-11-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotzone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetail',
            name='xCoord',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='locationdetail',
            name='yCoord',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
