# Generated by Django 3.1.2 on 2020-11-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotzone', '0002_auto_20201117_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='test',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
