# Generated by Django 3.1.2 on 2020-11-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotzone', '0005_patientdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetail',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotzone.patientdetail'),
            preserve_default=False,
        ),
    ]
