# Generated by Django 3.1.2 on 2020-11-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotzone', '0007_auto_20201117_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedetail',
            name='visitedLocation',
        ),
        migrations.AddField(
            model_name='visitedlocationdetail',
            name='caseNumber',
            field=models.ForeignKey(default=1001, on_delete=django.db.models.deletion.CASCADE, to='hotzone.casedetail'),
            preserve_default=False,
        ),
    ]
