# Generated by Django 3.1.3 on 2020-11-15 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='VirusDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commonName', models.CharField(max_length=100)),
                ('maxInfectionPeriod', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitedLocationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('category', models.CharField(choices=[('RESIDENCE', 'Residence'), ('WORKPLACE', 'Workplace'), ('VISIT', 'Visit')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('xCoord', models.DecimalField(decimal_places=2, max_digits=8)),
                ('yCoord', models.DecimalField(decimal_places=2, max_digits=8)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotzone.visitedlocationdetail')),
            ],
        ),
        migrations.CreateModel(
            name='CaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseNumber', models.CharField(max_length=5)),
                ('patient', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('caseType', models.CharField(choices=[('LOCAL', 'Local'), ('IMPORT', 'Import')], max_length=10)),
                ('virus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotzone.virusdetail')),
            ],
        ),
    ]
